DROP TYPE IF EXISTS specialties;
CREATE TYPE specialties AS ENUM (
    'Science',
    'Art',
    'Drama',
    'Music',
    'Gym'
);

CREATE TABLE school (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    school_date TEXT NOT NULL,
    student TEXT NOT NULL,
    english TEXT NOT NULL,
    math TEXT NOT NULL,
    specialty specialties NOT NULL,
    notes TEXT NOT NULL
);